In [1]:
import numpy as np

In [2]:
#creating a 5x4 array
array = np.arange(20).reshape(5,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [3]:
print(np.argmax(array))

19


In [4]:
print(np.argmax(array, axis=1))

[3 3 3 3 3]


In [5]:
print(np.argmax(array, axis=0))

[4 4 4 4]


In [6]:
array=np.array([
    [3,7,1],
    [10,3,2],
    [5,6,7]
])
print(array)

[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]


In [7]:
print(np.sort(array, axis=None))

[ 1  2  3  3  5  6  7  7 10]


In [8]:
print(np.sort(array, axis=1))

[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]


In [9]:
print(np.sort(array, axis=0))

[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]


In [10]:
#How to multiply two matrices in a single line using NumPy
matrix1=[
    [3,4,2],
    [5,1,8],
    [3,1,9]
]

matrix2=[
    [3,7,5],
    [2,9,8],
    [1,5,8]
]
result=np.dot(matrix1, matrix2)
print(result)

[[19 67 63]
 [25 84 97]
 [20 75 95]]


In [11]:
#How to print the checkerboard pattern of nxn using NumPy
n = 8

# Create a nxn matrix filled with 0
matrix = np.zeros((n, n), dtype=int)

# fill 1 with alternate rows and column
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

# Print the checkerboard pattern
for i in range(n):
    for j in range(n):
        print(matrix[i][j], end=" ")
    print()


0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


In [12]:
#How to reverse a NumPy array?
array = np.array([3, 6, 7, 2, 5, 1, 8])
reversedArray = np.flipud(array)
print(reversedArray)


[8 1 5 2 7 6 3]


In [13]:
#How to add rows and columns in NumPy array
array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])
newRow = np.array([2, 1, 8])
newArray = np.vstack((array, newRow))
print(newArray)


[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]
 [ 2  1  8]]


In [14]:
#How to find the mean of every NumPy array in the given list?
list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]
result = []
for i in range(len(list)):
    result.append(np.mean(list[i]))
print(result)


[5.5, 30.6, 34.0]


In [15]:
#How to sort the elements in the given array using Numpy
array = np.array([
    [3, 7, 1],
    [10, 3, 2],
    [5, 6, 7]
])
print(array)
print()
# Sort the whole array
print(np.sort(array, axis=None))
# Sort along each row
print(np.sort(array, axis=1))
# Sort along each column
print(np.sort(array, axis=0))


[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]

[ 1  2  3  3  5  6  7  7 10]
[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]
[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]


In [16]:
array = np.array([28, 13, 45, 12, 4, 8, 0])
print(array)
print(np.argsort(array))


[28 13 45 12  4  8  0]
[6 4 5 3 1 0 2]
